CREATE TABLE Users(
                      id int generated by default as identity primary key,
                      name varchar(100) not null,
                      email text not null unique,
                      password varchar not null,
                      role varchar check ( role in ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE Foods(
                      id int generated by default as identity primary key,
                      name varchar not null unique,
                      price numeric(10, 2) check ( price> 0 )
);

CREATE TABLE Bags(
                     id int generated  by default  as identity primary key ,
                     user_id int references Users(id),
                     food_id int references Foods(id),
                     quantity int check ( quantity > 0 )
);

CREATE VIEW order_vw as
select u.id as user_id,
       sum(f.price * b.quantity) as total_price
from Bags as b join Foods as f on b.food_id = f.id
               join Users as u on b.user_id = u.id
group by u.id;


insert into foods("name", "price") values ('pasta', 200);
insert into foods("name", "price") values ('meat', 300);
insert into foods("name", "price") values ('potato', 100);

